### ISSUE TITLE
odd issue

### ISSUE THREAD

**Issue by perlsol** [ReModded/ReWhitelist#1]
Hi, I have added this to velocity and added my testers etc, told my testers we are whitelist protected. One of my testers added a sibling (on the same IP address) to the "minecraft" /whitelist and not this velocity whitelist (they didn't know I meant velocity whitelist), they were able to connect! Any idea why this would happen... I assume the minecraft whitelist doesn't communicate with the velocity whitelist in any way?

**Comment by FantasyPvP** [comment]
did you enable the velocity whitelist? I'm pretty sure it's off by default.
the minecraft one doesn't have any impact on velocity from what I've seen while using both the vanilla one and the velocity one.

**Comment by perlsol** [comment]
yes it is enabled, I have a group called "players" and another called "admins", the only group that was off was "default" which I didn't use. which is why it was odd that they were able to join, hence the shout out to you. I will test this with my alt account later as that would be on the same IP address, but I assume (not looked at the code) that it's only done by name and not IP address

**Comment by szymonhajbowicz** [comment]
It may not be very well explained in the description, but the default whitelist serves as a global filtering switch. When default whitelist is enabled the plugin filters connections and processes the rest of the lists, when it is disabled it lets everyone in, skipping the rest of the lists

**Comment by perlsol** [comment]
well that explains it all :) not a bug then. ty
