### ISSUE TITLE
feature request: convert nick to uuid when possible

### ISSUE THREAD

**Issue by NyaomiDEV** [ReModded/ReWhitelist#3]
Providing an username does make sense for a no-hassle setup and it's all it's needed in offline mode. In online mode, however, the source of truth is the UUID.

There should be an opt-in mechanism that swaps out the username with the UUID on online mode, so that if the user changes their username, the whitelist will still recognize them.

**Comment by Twarug** [comment]
Rather then reopening feature request that already has been implemented, you can create new issue as it's bug.

**Comment by Twarug** [comment]
@KyrVorga you might want to check out new release, witch fixes both your issues (i hope). I the future, just open new Issue.
