### ISSUE TITLE
bug: whitelist remove

### ISSUE THREAD

**Issue by NyaomiDEV** [ReModded/ReWhitelist#4]
issuing `/whitelist remove <uuid>` on a previously added uuid removes it from RAM, but not from the actual file. Restarting the server or reloading the whitelists from disk makes deleted entries reappear again.

Tested on Velocity - ReWhitelist 1.0.0.

**Comment by thboehi** [comment]
Hey! I see that this issue exists since august, and not repaired. This project looks abandonned.
